### ISSUE TITLE
Vector vaccine for under 60s

### ISSUE THREAD

**Issue by MrToWy** [sibalzer/impfbot#126]
![image](https://user-images.githubusercontent.com/44198402/123435247-a77e0d00-d5cd-11eb-92de-d02db2b145f3.png)

You can book appointments for vector vaccine while under 60.
This option could be added to the bot as a config-entry in the [COMMON]-Area. :)

**Comment by sibalzer** [comment]
Thats new!
GET-Argument is
`showWithVectorVaccine=true`
