### ISSUE TITLE
Config creation interface if no config is provided

### ISSUE THREAD

**Issue by sibalzer** [sibalzer/impfbot#34]
A guided config setup via cli or even better gui, would great for inexperienced users.

Features
 - generating config file
 - easy to use & understand
 - step by step
 - integrated check (no validation script needed afterwards)

**Comment by paulypeter** [comment]
Can you specify your requirements?

**Comment by sibalzer** [comment]
Added. Btw your fork needs to reset hard to sibalzer/master. I had to rebase because of an information leak. Sorry for that.

**Comment by paulypeter** [comment]
I will implement that.

Alright, will do before starting this issue. You can assign me to it.

**Comment by paulypeter** [comment]
Some notes for myself

- [ ] implement GUI form
- [ ] implement CLI (mainly as fallback when GUI isn't working, e. g. on a headless system)

**Comment by paulypeter** [comment]
- [ ] add validation to form

**Comment by paulypeter** [comment]
@sibalzer Do you want the `[ADVANCED]` settings included? Otherwise, tested defaults could be fine.

**Comment by sibalzer** [comment]
I dont think this necessary, it should be as simple as possible (but if you have time, feel free). As email regex we could use the RFC 5322 compatible one from here: [emailregex](http://emailregex.com/ ), but this seems to be a science in itself. http://emailregex.com/

**Comment by paulypeter** [comment]
I thought about including that one, I didn't know whether you'd want that. I will include it.

**Comment by paulypeter** [comment]
Update: Now every notificator input is checked against a regex

**Comment by paulypeter** [comment]
closed with #83
