### ISSUE TITLE
Mac script doesnt work.

### ISSUE THREAD

**Issue by sibalzer** [sibalzer/impfbot#37]
https://old.reddit.com/r/de/comments/nkj3q6/ich_habe_einen_bot_zur_automatischen/gzmd5lw/

**Comment by paulypeter** [comment]
For macOS testing, [this](https://github.com/foxlet/macOS-Simple-KVM) could help.

I don't know much about the newer versions running on ARM though

**Comment by infclu** [comment]
It works on macOS 10.15/Intel. I navigated to /impfbot folder and did grant chmod +X permissions, though.

**Comment by sibalzer** [comment]
thanks 👍
