### ISSUE TITLE
Add please a Test for Groups

### ISSUE THREAD

**Issue by thetha** [sibalzer/impfbot#39]
There is no proof, but it looks like sometime are slot ONLY for groups.
Is there a way to check also for this?

**Comment by sibalzer** [comment]
I've just checked the api. there is a difference between individuals and groups in that the count parameter corresponds to the number of individuals and no birthdate is given, the age group is considered to be under 60. But not every vaccination center offers both. Currently the bot can only retrieve slots for individuals, for the next release there should be an option to retrieve groups as well.

Individual request
`https://www.impfportal-niedersachsen.de/portal/rest/appointments/findVaccinationCenterListFree/26871?stiko=&count=1&birthdate=-18147492000`

Group request
`https://www.impfportal-niedersachsen.de/portal/rest/appointments/findVaccinationCenterListFree/26871?stiko=&count=5`

**Comment by paulypeter** [comment]
If this one's already scheduled for v3.0.0, I'll look into it!

**Comment by paulypeter** [comment]
Sorry, I got vaccinated yesterday (yeay!), so I couldn't work on the issue yet.

**Comment by paulypeter** [comment]
The PR for this issue is #66

**Comment by paulypeter** [comment]
There will be another PR for inclusion of this feature in config generation

**Comment by sibalzer** [comment]
closed with #83
