### ISSUE TITLE
Show earliest vaccination slot date

### ISSUE THREAD

**Issue by sibalzer** [sibalzer/impfbot#58]
The response json has a `firstAppoinmentDateSorterOnline` value (unix timestamp in ms). Should be added to the alert message.

**Comment by paulypeter** [comment]
Is the `firstAppoinmentDateSorterOnline` element on the same level as `outOfStock` and so on? With no free slots, I can't look it up unfortunately

**Comment by sibalzer** [comment]
In the [api test file](tests/test_api_wrapper.py) is a valid response.

**Comment by sibalzer** [comment]
closed with #113
