### ISSUE TITLE
Telegram Notification is(maybe) Broken

### ISSUE THREAD

**Issue by thetha** [sibalzer/impfbot#62]
I got the console news:
2021-06-02 17:29:03 [INFO] Free slot! (2406) Moderna/mRNA
2021-06-02 17:29:03 [ERROR] Couldn't send Telegram message: Chat not found
Sleeping (898s/900s)

Very nice was the new open window! So I just had to click go.

Have a look at my config:

[TELEGRAM]
; true, wenn Telegram verwendet werden soll;  sonst false
enable_telegram=true
; Token muss zunächst generiert werden: https://t.me/BotFather
token=187726359*********************************
; User-ID des Empfängers: https://t.me/userinfobot
chat_id=https://t.me/************

**Comment by tiseidel** [comment]
The chat_id that you need is a numeric id you get by the @userinfobot

The data I get from the @userinfobot is:
> @username
> Id: 123456789
> First: Name
> Last: Name
> Lang: de

 The Id: **123456789** is what you need.

The https://t.me/username - Link with your unique username is not valid for the bot.

**Comment by sibalzer** [comment]
the problem got solved.
