### ISSUE TITLE
Password: "%" needs to be escaped

### ISSUE THREAD

**Issue by ronizzel** [sibalzer/impfbot#63]
Thanks for the amazing work! Finally I don't have to check all the time the Impfportal. 

One suggustion: A SMTP password containing will lead to an exception. You need to escape it by writing "%%" for one "%" in password. Maybe something to mention in the comment of config.ini.example?

**Comment by sibalzer** [comment]
Well thats not intended. We could also turn of interpolation by using RawConfigParser instead of ConfigParser
