### ISSUE TITLE
Document new config structure in README.md

### ISSUE THREAD

**Issue by paulypeter** [sibalzer/impfbot#69]
This is also required for v3.0.0!

We should update `README.md` to explain the (new) config structure and options.

TODO:

- [x] Update `README.md`
- [x] Create separate README in English
- [x] move `Contributing` section to separate file `CONTRIBUTING.md`

**Comment by paulypeter** [comment]
![Nice](https://user-images.githubusercontent.com/21948229/120800273-09ec6c00-c540-11eb-83ed-c0ab9d1beece.png)
Nice.

**Comment by sibalzer** [comment]
Yup i think the readme should be reworked in a few places. For example: I don't like the english section positioning, maybe it should be in a separate file.

Looking forward to release v3 this weekend.

**Comment by paulypeter** [comment]
I think I kind of agree. The text is quite long in German alone, maybe another file would be best.

Great!

**Comment by sibalzer** [comment]
closed by #83
