### ISSUE TITLE
raspberry pi

### ISSUE THREAD

**Issue by tkurzer** [sibalzer/impfbot#70]
under raspberry pi4 i get the following errors by starting linux_validate.sh:
File "src/validate_config.py", line 3, in <module> from alerts import alert
File "/usr/lib/impfbot-main/src/alerts.py", line 4, in <module> from telegram.ext import Updater
File "/home/pi/.local/lib/python3.7/site-packages/telegram/ext/__init__.py", line 21, in <module> from .basepersistence import BasePersistence
File "/home/pi/.local/lib/python3.7/site-packages/telegram/ext/basepersistence.py", line 25, in <module> from telegram import Bot
ImportError: cannot import name 'Bot' from 'telegram' (/home/pi/.local/lib/python3.7/site-packages/telegram/__init__.py)

**Comment by paulypeter** [comment]
[Have you installed "telegram"?](https://github.com/python-telegram-bot/python-telegram-bot/issues/395)

If so, that might be the culprit.

**Comment by paulypeter** [comment]
@sibalzer maybe there is an issue with `telegram=0.0.1` being listed in `requirements.txt`?

**Comment by sibalzer** [comment]
could you run:
`pip3 install -q -r requirements.txt`
and post the output?

**Comment by tkurzer** [comment]
requests==2.25.1

python_telegram_bot==13.3

telegram==0.0.1

 

 

Von: paulypeter ***@***.*** 
Gesendet: Freitag, 4. Juni 2021 15:25
An: sibalzer/impfbot
Cc: tkurzer; Author
Betreff: Re: [sibalzer/impfbot] raspberry pi (#70)

 

@sibalzer <https://github.com/sibalzer>  maybe there is an issue with telegram=0.0.1 being listed in requirements.txt?

**Comment by tkurzer** [comment]
pip3 install -r requirements.txt

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple

Requirement already satisfied: requests==2.25.1 in /home/pi/.local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (2.25.1)

Requirement already satisfied: python_telegram_bot==13.3 in /home/pi/.local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (13.3)

Requirement already satisfied: telegram==0.0.1 in /home/pi/.local/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (0.0.1)

Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.25.1->-r requirements.txt (line 1)) (2018.8.24)

Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests==2.25.1->-r requirements.txt (line 1)) (1.24.1)

Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.25.1->-r requirements.txt (line 1)) (2.6)

Requirement already satisfied: chardet<5,>=3.0.2 in /usr/lib/python3/dist-packages (from requests==2.25.1->-r requirements.txt (line 1)) (3.0.4)

Requirement already satisfied: tornado>=5.1 in /home/pi/.local/lib/python3.7/site-packages (from python_telegram_bot==13.3->-r requirements.txt (line 2)) (6.1)

Requirement already satisfied: pytz>=2018.6 in /usr/lib/python3/dist-packages (from python_telegram_bot==13.3->-r requirements.txt (line 2)) (2019.1)

Requirement already satisfied: APScheduler==3.6.3 in /home/pi/.local/lib/python3.7/site-packages (from python_telegram_bot==13.3->-r requirements.txt (line 2)) (3.6.3)

Requirement already satisfied: setuptools>=0.7 in /usr/lib/python3/dist-packages (from APScheduler==3.6.3->python_telegram_bot==13.3->-r requirements.txt (line 2)) (40.8.0)

Requirement already satisfied: tzlocal>=1.2 in /home/pi/.local/lib/python3.7/site-packages (from APScheduler==3.6.3->python_telegram_bot==13.3->-r requirements.txt (line 2)) (2.1)

Requirement already satisfied: six>=1.4.0 in /usr/lib/python3/dist-packages (from APScheduler==3.6.3->python_telegram_bot==13.3->-r requirements.txt (line 2)) (1.12.0)

 

Von: sibalzer ***@***.*** 
Gesendet: Freitag, 4. Juni 2021 17:01
An: sibalzer/impfbot
Cc: tkurzer; Author
Betreff: Re: [sibalzer/impfbot] raspberry pi (#70)

 

could you run:
pip3 install -r requirements.txt
and post the output?

**Comment by tkurzer** [comment]
After doing this pip install -U python-telegram-bot
It look better:
 
./linux_validate.sh
2021-06-05 10:35:12 [INFO] validate config.ini
2021-06-05 10:35:12 [INFO] settings validation finished
Do you want to send a test message? yes/no
yes
2021-06-05 10:35:21 [INFO] [EMAIL] send_mail is not set to true skipping
2021-06-05 10:35:21 [INFO] [TELEGRAM] try to send telegram message
2021-06-05 10:35:21 [INFO] [TELEGRAM] sending telegram message was successful
2021-06-05 10:35:21 [INFO] [WEBBROWSER] try to open browser
2021-06-05 10:35:21 [INFO] [WEBBROWSER] open browser was successful
2021-06-05 10:35:21 [INFO] Finished: Sending test massages
2021-06-05 10:35:21 [INFO] finished validation script

 

 

Von: sibalzer ***@***.*** 
Gesendet: Freitag, 4. Juni 2021 17:01
An: sibalzer/impfbot
Cc: tkurzer; Author
Betreff: Re: [sibalzer/impfbot] raspberry pi (#70)

 

could you run:
pip3 install -r requirements.txt
and post the output?

**Comment by Triple1090** [comment]
Hi, I get the same error after _pip install -U python-telegram-bot_ on my Raspberry.

`Traceback (most recent call last):
  File "src/validate_config.py", line 3, in <module>
    from alerts import alert
  File "/home/pi/Documents/Impfbot/impfbot-main/src/alerts.py", line 4, in <module>
    from telegram.ext import Updater
  File "/home/pi/.local/lib/python3.7/site-packages/telegram/ext/__init__.py", line 21, in <module>
    from .basepersistence import BasePersistence
  File "/home/pi/.local/lib/python3.7/site-packages/telegram/ext/basepersistence.py", line 25, in <module>
    from telegram import Bot
ImportError: cannot import name 'Bot' from 'telegram' (/home/pi/.local/lib/python3.7/site-packages/telegram/__init__.py)
`

**Comment by sibalzer** [comment]
do you currently run python on the pi for anything else?

**Comment by Triple1090** [comment]
> 
> 
> do you currently run python on the pi for anything else?

Hi, yes, PiHole is currently running on the Pi. Apart from that, the Pi is on idle.

**Comment by Triple1090** [comment]
Update: I commented the Telegram-parting in settings.py out. Now it's running fine on the Pi.

**Comment by sibalzer** [comment]
Unfortunately no. F12 is your friend.

**Comment by sibalzer** [comment]
I am currently adding apprise #51. I'm also replacing the telegram backend with the apprise one at the same time. That should fix it.

**Comment by Muehli25** [comment]
had the same issue, using a venv fixed it for me, maybe another installes pip package is causing this issue

**Comment by Aletho** [comment]
Either one or both fixed it for me. Can't remember the sequence though. 
`pip3 uninstall telegram`
`pip3 uninstall python_telegram_bot`

Followed by
`pip3 install -r requirements.txt`

**Comment by sibalzer** [comment]
should be fixed with #83 (new backend)
