### ISSUE TITLE
Docker image for Raspberry Pi (arm64) missing

### ISSUE THREAD

**Issue by pixiono** [sibalzer/impfbot#77]
Hello, 

I was just about to set up the project on my Raspberry Pi, but found that the image is only provided for the amd64 architecture:

`pixiono@pi:~/impfbot/docker$ docker image inspect ghcr.io/sibalzer/impfbot:latest | grep "amd"
        "Architecture": "amd64",`

Since I believe that this application scenario could easily be made possible I have prepared a PR: https://github.com/sibalzer/impfbot/pull/76

I used this to enable a multi-arch build: https://github.com/docker/build-push-action

Since I have never worked with GitHub workflows before, I can't verify if this works.

**Comment by pixiono** [comment]
I am on it, but am currently stuck with an error message:
`#15 16.09 subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.
418
#15 ERROR: executor failed running [/dev/.buildkit_qemu_emulator /bin/sh -c pip install -r requirements.txt]: exit code: 1
419
------
420
 > [linux/arm64 4/6] RUN pip install -r requirements.txt:
421
------
422
Dockerfile:6
423
--------------------
424
   4 |     
425
   5 |     COPY requirements.txt .
426
   6 | >>> RUN pip install -r requirements.txt
427
   7 |     
428
   8 |     COPY src/ .
429
--------------------
430
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/dev/.buildkit_qemu_emulator /bin/sh -c pip install -r requirements.txt]: exit code: 1
431
Error: buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = executor failed running [/dev/.buildkit_qemu_emulator /bin/sh -c pip install -r requirements.txt]: exit code: 1`

**Comment by b-reich** [comment]
I can do this

**Comment by sibalzer** [comment]
see #76

**Comment by sibalzer** [comment]
closed with #122
