### ISSUE TITLE
docker composes creates config.ini as folder

### ISSUE THREAD

**Issue by DennisWilken** [sibalzer/impfbot#79]
If you want to use the docker-compose file you need to make sure that the config.ini file already exists. Otherwise, docker will create a folder with the name config.ini that I couldn't delete while docker was running. Maybe you could add a comment to the compose file? Took me some time to solve this problem. 

Do I have to restart my docker container after adding new users to the config.ini or the config.ini read automatically?

**Comment by sibalzer** [comment]
I will add a comment. when changing the config, the container must be restarted.
