### ISSUE TITLE
Config properties in the example do not match requirements in Docker-Compose

### ISSUE THREAD

**Issue by MaggiWuerze** [sibalzer/impfbot#85]
I copied and modified the provided config.example.ini but the log of docker-compose tells me that fields are missing that are in the config with either slightly different name or in a different language.

He wants geburtstag but the config says birthdate (same for zipcode).
 
He wants enable_telegram but the config only has enable under [TELEGRAM]

**Comment by sibalzer** [comment]
Please use the example config from 050562b6a3. The docker image is not up-to-date. (deploy pipeline broken)

**Comment by MaggiWuerze** [comment]
yeah, i just noticed that. Thanks

**Comment by sibalzer** [comment]
Pipeline is fixed #86 (no idea what the google release please action had for a problem there). The Docker image is now up-to-date.
