### ISSUE TITLE
Telegram group IDs stopped working in 3.0 or logging problem 

### ISSUE THREAD

**Issue by DennisWilken** [sibalzer/impfbot#91]
In version 2.0, I used group IDs to send messages directly to Telegram groups. The group IDs have a minus sign. A description, how to find the group ID is given [here](https://stackoverflow.com/questions/32423837/telegram-bot-how-to-get-a-group-chat-id).

As soon as I add a group ID to my chat_ids, the logs on start show `chat_ids: not set`. I couldn't validate if the IDs are still used (see [here](https://github.com/sibalzer/impfbot/issues/90).

In the logs, the entries of the Email/receivers list are not separated by any character. The same is true for the chat_ids.

**Comment by paulypeter** [comment]
I'll fix the regex.
