### ISSUE TITLE
add custom prefix for alert messages

### ISSUE THREAD

**Issue by sibalzer** [sibalzer/impfbot#95]
We could add some custom prefix (in config) to the message eg:
[My Group bot for 49123] Freier Impfslot (11)! AstraZeneca/Vector

Dunno where to put in the config. `[ADVANCED] custom_message_prefix` maybe?

_Originally posted by @sibalzer in https://github.com/sibalzer/impfbot/issues/5#issuecomment-857458719_

**Comment by paulypeter** [comment]
> Dunno where to put in the config. [ADVANCED] custom_message_prefix maybe?

Sounds good, I wouldn't know where else to put it, either
